import type { Metadata } from "next";
import "../globals.css";
import styles from './layout.module.css'
import NavBar from "./NavBar";
import {VT323} from 'next/font/google'

//VT323 Font properties
const vt323 = VT323({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Sal Surf School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className={`${vt323.className} ${styles.header}`}>
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
